# Generated by Django 4.2.6 on 2024-03-29 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('effect', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('years', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flavor_text', models.CharField(max_length=50)),
                ('effect', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('effect', models.CharField(max_length=50)),
                ('story', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_event', to='kingdomdeathapi.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ExpansionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FightingArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('effect', models.CharField(max_length=50)),
                ('expansion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expansion_fighting_art', to='kingdomdeathapi.expansiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Impairment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('effect', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_game_master', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('survival_limit', models.IntegerField()),
                ('population', models.IntegerField()),
                ('game_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='kingdomdeathapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specialist_effect', models.CharField(max_length=50)),
                ('master_effect', models.CharField(max_length=50)),
                ('expansion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expansion_weapon_proficiency', to='kingdomdeathapi.expansiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('survival', models.IntegerField()),
                ('insanity', models.IntegerField()),
                ('hunt_experience', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('movement', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('evasion', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('luck', models.IntegerField()),
                ('understanding', models.IntegerField()),
                ('courage', models.IntegerField()),
                ('head_armor', models.IntegerField()),
                ('head_wound', models.BooleanField(default=False)),
                ('arm_armor', models.IntegerField()),
                ('arm_light_wound', models.BooleanField(default=False)),
                ('arm_heavy_wound', models.BooleanField(default=False)),
                ('body_armor', models.IntegerField()),
                ('body_light_wound', models.BooleanField(default=False)),
                ('body_heavy_wound', models.BooleanField(default=False)),
                ('waist_armor', models.IntegerField()),
                ('waist_light_wound', models.BooleanField(default=False)),
                ('waist_heavy_wound', models.BooleanField(default=False)),
                ('leg_armor', models.IntegerField()),
                ('leg_light_wound', models.BooleanField(default=False)),
                ('leg_heavy_wound', models.BooleanField(default=False)),
                ('ability', models.ManyToManyField(blank=True, related_name='applicable_survivor', to='kingdomdeathapi.ability')),
                ('disorder', models.ManyToManyField(blank=True, related_name='applicable_survivor', to='kingdomdeathapi.disorder')),
                ('fighting_art', models.ManyToManyField(blank=True, related_name='applicable_survivor', to='kingdomdeathapi.fightingart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survivors', to='kingdomdeathapi.player')),
                ('weapon_proficiency', models.ManyToManyField(blank=True, related_name='applicable_survivor', to='kingdomdeathapi.weaponproficiency')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='kingdomdeathapi.resource')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='kingdomdeathapi.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_settlement', to='kingdomdeathapi.event')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='kingdomdeathapi.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_session', to='kingdomdeathapi.player')),
                ('players', models.ManyToManyField(related_name='participating', to='kingdomdeathapi.player')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_session', to='kingdomdeathapi.settlement')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicable_resource', to='kingdomdeathapi.resourcetype'),
        ),
        migrations.CreateModel(
            name='ProficiencyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('survivor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon_proficiency_level', to='kingdomdeathapi.survivor')),
                ('weapon_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survivor_weapon_proficiency', to='kingdomdeathapi.weaponproficiency')),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nemesis', models.BooleanField(default=False)),
                ('expansion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expansion_monster', to='kingdomdeathapi.expansiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.BooleanField(default=False)),
                ('milestone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='kingdomdeathapi.milestonetype')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achieved_milestone', to='kingdomdeathapi.settlement')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='expansion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expansion_event', to='kingdomdeathapi.expansiontype'),
        ),
        migrations.AddField(
            model_name='disorder',
            name='expansion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expansion_disorder', to='kingdomdeathapi.expansiontype'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='expansion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expansion_campaign', to='kingdomdeathapi.expansiontype'),
        ),
        migrations.AddField(
            model_name='ability',
            name='expansion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expansion_ability', to='kingdomdeathapi.expansiontype'),
        ),
    ]
