from django.db import models

class Survivor(models.Model):
    user = models.ForeignKey("Player", on_delete=models.CASCADE, related_name="survivors")
    name = models.CharField(max_length=50)
    survival = models.IntegerField()
    insanity = models.IntegerField()
    hunt_experience = models.IntegerField()
    gender = models.CharField(max_length=50)
    movement = models.IntegerField()
    accuracy = models.IntegerField()
    strength = models.IntegerField()
    evasion = models.IntegerField()
    speed = models.IntegerField()
    luck = models.IntegerField()
    understanding = models.IntegerField()
    courage = models.IntegerField()
    head_armor = models.IntegerField()
    head_wound = models.BooleanField(default=False)
    arm_armor = models.IntegerField()
    arm_light_wound = models.BooleanField(default=False)
    arm_heavy_wound = models.BooleanField(default=False)
    body_armor = models.IntegerField()
    body_light_wound = models.BooleanField(default=False)
    body_heavy_wound = models.BooleanField(default=False)
    waist_armor = models.IntegerField()
    waist_light_wound = models.BooleanField(default=False)
    waist_heavy_wound = models.BooleanField(default=False)
    leg_armor = models.IntegerField()
    leg_light_wound = models.BooleanField(default=False)
    leg_heavy_wound = models.BooleanField(default=False)
    weapon_proficiency = models.ForeignKey("WeaponProficiency", on_delete=models.CASCADE, related_name="applicable_survivor")
    fighting_art = models.ForeignKey("FightingArt", on_delete=models.CASCADE, related_name="applicable_survivor")
    disorder = models.ForeignKey("Disorder", on_delete=models.CASCADE, related_name="applicable_survivor")
    ability = models.ForeignKey("Ability", on_delete=models.CASCADE, related_name="applicable_survivor")